### ISSUE TITLE
ImportError on Travis with pip-installed ModernGL

### ISSUE THREAD

**Issue by Korijn** [cprogrammer1994/ModernGL#113]
Importing ModernGL on Travis gives me the following error:

```
virtualenv/python3.6.2rc1/lib/python3.6/site-packages/ModernGL/__init__.py:8: in <module>
    from .mgl import Error
E   ImportError: /home/travis/virtualenv/python3.6.2rc1/lib/python3.6/site-packages/ModernGL/mgl.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Z17MGLContext_shaderILi0EEP9MGLShaderP10MGLContextP7_object
During handling of the above exception, another exception occurred:
tests/test_radiant.py:2: in <module>
    import ModernGL
../../../virtualenv/python3.6.2rc1/lib/python3.6/site-packages/ModernGL/__init__.py:22: in <module>
    raise ImportError(_IMPORT_ERROR) from None
E   ImportError: No implementation found for ModernGL
E   Are you sure the source code is compiled properly?
```

I'm not sure if I need to add anythin to my travis config to enable support? I simply installed latest ModernGL with pip for latest Python 3.6.

**Comment by cprogrammer1994** [comment]
I was able to reproduce the [problem](https://travis-ci.org/cprogrammer1994/ModernGL/builds/246077610?utm_source=github_status&utm_medium=notification).

**Comment by cprogrammer1994** [comment]
Temporary fix: use `g++4.8`

> I am upgrading my local build cluster, I will be able to upload wheels for python3.6 on linux.

Here is a working travis config:

```yml
language: python

os:
  - linux

sudo: false

matrix:
  fast_finish: true

python:
  - 3.6
  - 3.5
  - 3.4

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

install:
  - CC=gcc-4.8 CXX=g++-4.8 pip install ModernGL
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi
  - python -c "import ModernGL"

script: python -m ModernGL
```

**xvfb** does not provide the latest Mesa Driver 😞
